### ISSUE TITLE
Handle other headers than redirect

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-redirects#1]
Module should sport any kind of headers including defaults.

From what I understand a header is a key and a value which is in turn parsed into a string like so:

```
#  KEY                               |  VALUE
Content-Security-Policy = "upgrade-insecure-requests"
```
Now some headers can sports multiple values like the Netlify [example](https://docs.netlify.com/routing/headers/#multi-value-headers)

So in our module API we need 

```
- for: /that-page
   headers:
     content-security-policy: upgrade-insecure-requests
``` 
OR
```
- for: /that-page
   headers:
     content-security-policy: 
        - default-src 'self'
        - style-src 'self' 'unsafe-inline' https://cloud.typography.com
``` 

See https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by budparr** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
